name: traccar_client
description: "Traccar Client"
publish_to: 'none'
version: 9.4.3+103

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  file_picker: ^10.2.0
  firebase_analytics: ^11.5.1
  firebase_core: ^3.15.0
  firebase_crashlytics: ^4.3.8
  firebase_messaging: ^15.2.8
  flutter:
    sdk: flutter
  flutter_background_geolocation: ^4.16.12
  flutter_image_compress: ^2.4.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  get: ^4.7.2
  image_picker: ^1.1.2
  intl: any
  mobile_scanner: ^7.0.1
  quick_actions: ^1.1.0
  rate_my_app: ^2.3.2
  shared_preferences: ^2.5.3
  shared_preferences_android: ^2.4.10
  signature: ^6.3.0
  sn_progress_dialog:
    git:
      url: https://github.com/digital-phantom-official/Flutter-Progress-Dialog
      ref: develop
  video_compress: ^3.1.4
  wakelock_partial_android: ^1.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
